### PR TITLE
Update Updater.py

### PR DESCRIPTION
**Pull request by backslashin**
Updated the updater, your welcome :)

### CODE REVIEW

**Comment by cabiste69** [comment]
without you my deer friend we would've never been able to fix this error

**Comment by backslashin** [comment]
sadly i cant manually fix this typo ;(
image

**Comment by cabiste69** [comment]
> sadly i cant manually fix this typo ;( image

that was not a typo :)

**Comment by backslashin** [comment]
you f##king calling me a deer?

**Comment by backslashin** [comment]
>:(

**Pull request merged**
