### PR TITLE
DisplayText and other text GUI optimizations, Steam Deck fixes, FALLBACK removal, and Ban and Kick Nut Almost Done

### PR DESCRIPTION
**Pull request by OrsellGaming**
The stuff for DisplayText should be done, and text wrapping for it. I also added text wrapping for InputPrompts so longer prompts can be used in the config. It will detect "\n"s.

Made fixes for the Steam Deck. The p2mm folder will now be on the Desktop, it also should now actually start Portal 2. Changed the default launch window size width to 800 to accommodate the Steam Decks screen if the launcher is launched in Gaming Mode. One current bug, though, is that it is not pinging 8.8.8.8 to check if it has internet. Even if I am connected to the internet. I still need to continue testing to determine and fix the issue.

Removed the FALLBACK stuff; it is not needed and is useless. The original point was to have another set of ModFiles in case the user isn't connected to the internet. You need the internet to have users join you for P2MM. So it's pointless, and so it's removed.

Data System stuff is still not done yet, so I will continue working on that. I just wanted to get my GUI changes for the launcher out before I continued the Data System.

The French translation needs a look over and fixed to accommodate accurate French translations. Google Translate won't cut it.

I am almost done with ban.nut and kick.nut chat commands, I need to add their Data System functionality, and I should be done.

### CODE REVIEW

**Comment by OrsellGaming** [comment]
Few corrections to the DisplayText wrapping. DisplayText will wrap text as inputed with the need for "\n"s. The prompt config option in Configs.py as been made in MainWindow.py to detect "\n"s and make a newline. DisplayText as a different system of wrapping than the InputPrompts, still experimenting and testing those two. The InputText one involves splitting the prompt into parts at each "\n" then display the text on a newline from there. Works well and but doesn't work well with DisplayText because it calls on other things in MainWindow.py. I will another time get it working with DisplayText but for now DisplayText will use a system that will wrap and detect if words are near a window edge. The way InputPrompt's wrapping works doesnt rely on this since its always in a fixed position.

**Comment by OrsellGaming** [comment]
Couldn't this have been just left open instead of closed?

**Comment by cabiste69** [comment]
since it's already merged there's no need to keep it open

**Comment by OrsellGaming** [comment]
It doesn't say it was merged though?

**Pull request closed without merging**
