### PR TITLE
Russian translation & other translation files fixes

### PR DESCRIPTION
**Pull request by Blueberryy**

### CODE REVIEW

**Comment by OrsellGaming** [comment]
Hi @Blueberryy, it appears you have used the wrong branch of the repository. The `dev` branch has more up-to-date translations as well as a `basemod_ui` file under `ModFiles/install_dlc/resources` that needs a Russian file. You should be able to pull the Russian one Portal 2 already has but you need to copy the contents of the P2MM from the English one. It should be separated from the other translations Portal 2 uses. Thanks for your contribution.

**Comment by Blueberryy** [comment]
> Hi @Blueberryy, it appears you have used the wrong branch of the repository. The `dev` branch has more up-to-date translations as well as a `basemod_ui` file under `ModFiles/install_dlc/resources` that needs a Russian file. You should be able to pull the Russian one Portal 2 already has but you need to copy the contents of the P2MM from the English one. It should be separated from the other translations Portal 2 uses. Thanks for your contribution.

Oh thanks for the info! I will close this PR for now and see what dev branch have.

**Comment by OrsellGit** [comment]
Hey @Blueberryy are you still interested in helping translate P2:MM?

**Comment by Blueberryy** [comment]
> Hey @Blueberryy are you still interested in helping translate P2:MM?

Not at the moment.

**Pull request closed without merging**
